name: Main - Deploy Production Pipeline
run-name: "Release - ${{ github.event.repository.name }} Build #${{ github.run_number }}"

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:

    # Dump GitHub Context
    - name: Dump GitHub Context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo '**GitHub Context**' >> GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$GITHUB_CONTEXT" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

