name: Main - Deploy Staging Pipeline
run-name: "Main - ${{ github.event.repository.name }} Build #${{ github.run_number }}"

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:

    # Dump GitHub Context
    - name: Dump GitHub Context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo '**GitHub Context**' >> GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$GITHUB_CONTEXT" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

